version: '2'

services:
  sentry-redis:
    image: redis
    restart: always

  sentry-postgres:
    environment:
    - POSTGRES_PASSWORD=secret
    - POSTGRES_USER=sentry
    image: postgres
    restart: always

  my-sentry:
    environment:
    - SENTRY_SECRET_KEY='${SECRET_KEY}'
    - SENTRY_REDIS_HOST=redis
    links:
    - sentry-redis:redis
    - sentry-postgres:postgres
    image: sentry
    ports:
    - "8080:9000"

  sentry-cron:
    environment:
    - SENTRY_SECRET_KEY='${SECRET_KEY}'
    - SENTRY_REDIS_HOST=redis
    links:
    - sentry-postgres:postgres
    - sentry-redis:redis
    image: sentry
    command: sentry celery beat


  sentry-worker-1:
    environment:
    - SENTRY_SECRET_KEY='${SECRET_KEY}'
    - SENTRY_REDIS_HOST=redis
    links:
    - sentry-postgres:postgres
    - sentry-redis:redis
    image: sentry
    command: sentry run worker
