version: '2'

services:
  sentry-redis:
    image: redis
    container_name: sentry-redis
    restart: always

  sentry-postgres:
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: always
    container_name: sentry-postgres
    volumes:
      - ./data:/var/lib/postgresql/data

  sentry:
    image: sentry
    environment:
      - SENTRY_SECRET_KEY=${SECRET_KEY}
      - SENTRY_REDIS_HOST=sentry-redis
      - SENTRY_POSTGRES_HOST=sentry-postgres
      - SENTRY_DB_USER=${POSTGRES_USER}
      - SENTRY_DB_PASSWORD=${POSTGRES_PASSWORD}

  sentry-cron:
    extends: sentry
    command: sentry run cron

  sentry-worker-1:
    extends: sentry
    command: sentry run worker
